// Generated by gencpp from file kobuki_fleet_msgs/BiddingOfferRequest.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_BIDDINGOFFERREQUEST_H
#define KOBUKI_FLEET_MSGS_MESSAGE_BIDDINGOFFERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kobuki_fleet_msgs/Bidding.h>

namespace kobuki_fleet_msgs
{
template <class ContainerAllocator>
struct BiddingOfferRequest_
{
  typedef BiddingOfferRequest_<ContainerAllocator> Type;

  BiddingOfferRequest_()
    : bidd()
    , cancelOffer(false)  {
    }
  BiddingOfferRequest_(const ContainerAllocator& _alloc)
    : bidd(_alloc)
    , cancelOffer(false)  {
    }



   typedef  ::kobuki_fleet_msgs::Bidding_<ContainerAllocator>  _bidd_type;
  _bidd_type bidd;

   typedef uint8_t _cancelOffer_type;
  _cancelOffer_type cancelOffer;




  typedef boost::shared_ptr< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BiddingOfferRequest_

typedef ::kobuki_fleet_msgs::BiddingOfferRequest_<std::allocator<void> > BiddingOfferRequest;

typedef boost::shared_ptr< ::kobuki_fleet_msgs::BiddingOfferRequest > BiddingOfferRequestPtr;
typedef boost::shared_ptr< ::kobuki_fleet_msgs::BiddingOfferRequest const> BiddingOfferRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kobuki_fleet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'kobuki_fleet_msgs': ['/home/odroid/car-whisper/src/kobuki_fleet/kobuki_fleet_msgs/msg', '/home/odroid/car-whisper/devel/share/kobuki_fleet_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "223305b23ffe109fc780241bd9393edf";
  }

  static const char* value(const ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x223305b23ffe109fULL;
  static const uint64_t static_value2 = 0xc780241bd9393edfULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/BiddingOfferRequest";
  }

  static const char* value(const ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/Bidding bidd\n\
bool cancelOffer\n\
\n\
================================================================================\n\
MSG: kobuki_fleet_msgs/Bidding\n\
Header header\n\
string machineName\n\
string robotName\n\
uint16 cost    \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bidd);
      stream.next(m.cancelOffer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BiddingOfferRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kobuki_fleet_msgs::BiddingOfferRequest_<ContainerAllocator>& v)
  {
    s << indent << "bidd: ";
    s << std::endl;
    Printer< ::kobuki_fleet_msgs::Bidding_<ContainerAllocator> >::stream(s, indent + "  ", v.bidd);
    s << indent << "cancelOffer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cancelOffer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_BIDDINGOFFERREQUEST_H
