// Generated by gencpp from file kobuki_fleet_msgs/BiddingOffer.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_BIDDINGOFFER_H
#define KOBUKI_FLEET_MSGS_MESSAGE_BIDDINGOFFER_H

#include <ros/service_traits.h>


#include <kobuki_fleet_msgs/BiddingOfferRequest.h>
#include <kobuki_fleet_msgs/BiddingOfferResponse.h>


namespace kobuki_fleet_msgs
{

struct BiddingOffer
{

typedef BiddingOfferRequest Request;
typedef BiddingOfferResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BiddingOffer
} // namespace kobuki_fleet_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kobuki_fleet_msgs::BiddingOffer > {
  static const char* value()
  {
    return "c40febe48f5b899764d93ce83ac485a7";
  }

  static const char* value(const ::kobuki_fleet_msgs::BiddingOffer&) { return value(); }
};

template<>
struct DataType< ::kobuki_fleet_msgs::BiddingOffer > {
  static const char* value()
  {
    return "kobuki_fleet_msgs/BiddingOffer";
  }

  static const char* value(const ::kobuki_fleet_msgs::BiddingOffer&) { return value(); }
};


// service_traits::MD5Sum< ::kobuki_fleet_msgs::BiddingOfferRequest> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::BiddingOffer > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::BiddingOfferRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::BiddingOffer >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::BiddingOfferRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::BiddingOfferRequest> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::BiddingOffer > 
template<>
struct DataType< ::kobuki_fleet_msgs::BiddingOfferRequest>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::BiddingOffer >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::BiddingOfferRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kobuki_fleet_msgs::BiddingOfferResponse> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::BiddingOffer > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::BiddingOfferResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::BiddingOffer >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::BiddingOfferResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::BiddingOfferResponse> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::BiddingOffer > 
template<>
struct DataType< ::kobuki_fleet_msgs::BiddingOfferResponse>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::BiddingOffer >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::BiddingOfferResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_BIDDINGOFFER_H
