// Generated by gencpp from file kobuki_fleet_msgs/ConnectionState.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_CONNECTIONSTATE_H
#define KOBUKI_FLEET_MSGS_MESSAGE_CONNECTIONSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kobuki_fleet_msgs
{
template <class ContainerAllocator>
struct ConnectionState_
{
  typedef ConnectionState_<ContainerAllocator> Type;

  ConnectionState_()
    : state(0)  {
    }
  ConnectionState_(const ContainerAllocator& _alloc)
    : state(0)  {
    }



   typedef uint8_t _state_type;
  _state_type state;


    enum { WIFI = 0u };
     enum { NEOCORTEC = 1u };
     enum { DISCONNECTED = 2u };
 

  typedef boost::shared_ptr< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> const> ConstPtr;

}; // struct ConnectionState_

typedef ::kobuki_fleet_msgs::ConnectionState_<std::allocator<void> > ConnectionState;

typedef boost::shared_ptr< ::kobuki_fleet_msgs::ConnectionState > ConnectionStatePtr;
typedef boost::shared_ptr< ::kobuki_fleet_msgs::ConnectionState const> ConnectionStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kobuki_fleet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'kobuki_fleet_msgs': ['/home/odroid/car-whisper/src/kobuki_fleet/kobuki_fleet_msgs/msg', '/home/odroid/car-whisper/devel/share/kobuki_fleet_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "018c1b9d0899955a1f2147e56051f53b";
  }

  static const char* value(const ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x018c1b9d0899955aULL;
  static const uint64_t static_value2 = 0x1f2147e56051f53bULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/ConnectionState";
  }

  static const char* value(const ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 state\n\
uint8 WIFI 			= 0\n\
uint8 NEOCORTEC   	= 1\n\
uint8 DISCONNECTED 	= 2\n\
";
  }

  static const char* value(const ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ConnectionState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kobuki_fleet_msgs::ConnectionState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_CONNECTIONSTATE_H
