// Generated by gencpp from file kobuki_fleet_msgs/CreateNewTask.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_CREATENEWTASK_H
#define KOBUKI_FLEET_MSGS_MESSAGE_CREATENEWTASK_H

#include <ros/service_traits.h>


#include <kobuki_fleet_msgs/CreateNewTaskRequest.h>
#include <kobuki_fleet_msgs/CreateNewTaskResponse.h>


namespace kobuki_fleet_msgs
{

struct CreateNewTask
{

typedef CreateNewTaskRequest Request;
typedef CreateNewTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreateNewTask
} // namespace kobuki_fleet_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kobuki_fleet_msgs::CreateNewTask > {
  static const char* value()
  {
    return "fbe5d6e4f29a92d827d682acfefce3c3";
  }

  static const char* value(const ::kobuki_fleet_msgs::CreateNewTask&) { return value(); }
};

template<>
struct DataType< ::kobuki_fleet_msgs::CreateNewTask > {
  static const char* value()
  {
    return "kobuki_fleet_msgs/CreateNewTask";
  }

  static const char* value(const ::kobuki_fleet_msgs::CreateNewTask&) { return value(); }
};


// service_traits::MD5Sum< ::kobuki_fleet_msgs::CreateNewTaskRequest> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::CreateNewTask > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::CreateNewTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::CreateNewTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::CreateNewTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::CreateNewTaskRequest> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::CreateNewTask > 
template<>
struct DataType< ::kobuki_fleet_msgs::CreateNewTaskRequest>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::CreateNewTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::CreateNewTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kobuki_fleet_msgs::CreateNewTaskResponse> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::CreateNewTask > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::CreateNewTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::CreateNewTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::CreateNewTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::CreateNewTaskResponse> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::CreateNewTask > 
template<>
struct DataType< ::kobuki_fleet_msgs::CreateNewTaskResponse>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::CreateNewTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::CreateNewTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_CREATENEWTASK_H
