// Generated by gencpp from file kobuki_fleet_msgs/CreateNewTaskRequest.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_CREATENEWTASKREQUEST_H
#define KOBUKI_FLEET_MSGS_MESSAGE_CREATENEWTASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kobuki_fleet_msgs
{
template <class ContainerAllocator>
struct CreateNewTaskRequest_
{
  typedef CreateNewTaskRequest_<ContainerAllocator> Type;

  CreateNewTaskRequest_()
    : destinationName()
    , robotName()
    , taskType(0)
    , taskMaterialType(0)  {
    }
  CreateNewTaskRequest_(const ContainerAllocator& _alloc)
    : destinationName(_alloc)
    , robotName(_alloc)
    , taskType(0)
    , taskMaterialType(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _destinationName_type;
  _destinationName_type destinationName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotName_type;
  _robotName_type robotName;

   typedef uint16_t _taskType_type;
  _taskType_type taskType;

   typedef uint16_t _taskMaterialType_type;
  _taskMaterialType_type taskMaterialType;


    enum { REPLENISHMENT = 1u };
     enum { DELIVERY = 2u };
     enum { GOTO = 3u };
     enum { CALL = 4u };
     enum { typeA = 1u };
     enum { typeB = 2u };
 

  typedef boost::shared_ptr< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CreateNewTaskRequest_

typedef ::kobuki_fleet_msgs::CreateNewTaskRequest_<std::allocator<void> > CreateNewTaskRequest;

typedef boost::shared_ptr< ::kobuki_fleet_msgs::CreateNewTaskRequest > CreateNewTaskRequestPtr;
typedef boost::shared_ptr< ::kobuki_fleet_msgs::CreateNewTaskRequest const> CreateNewTaskRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kobuki_fleet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'kobuki_fleet_msgs': ['/home/odroid/car-whisper/src/kobuki_fleet/kobuki_fleet_msgs/msg', '/home/odroid/car-whisper/devel/share/kobuki_fleet_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f13741139768cc895678082f964ed4df";
  }

  static const char* value(const ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf13741139768cc89ULL;
  static const uint64_t static_value2 = 0x5678082f964ed4dfULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/CreateNewTaskRequest";
  }

  static const char* value(const ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string destinationName\n\
string robotName\n\
\n\
uint16 REPLENISHMENT=1\n\
uint16 DELIVERY=2\n\
uint16 GOTO=3\n\
uint16 CALL=4\n\
uint16 taskType\n\
\n\
uint16 typeA=1\n\
uint16 typeB=2\n\
uint16 taskMaterialType\n\
";
  }

  static const char* value(const ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destinationName);
      stream.next(m.robotName);
      stream.next(m.taskType);
      stream.next(m.taskMaterialType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CreateNewTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kobuki_fleet_msgs::CreateNewTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "destinationName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.destinationName);
    s << indent << "robotName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotName);
    s << indent << "taskType: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.taskType);
    s << indent << "taskMaterialType: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.taskMaterialType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_CREATENEWTASKREQUEST_H
