// Generated by gencpp from file kobuki_fleet_msgs/GetCurrentTask.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_GETCURRENTTASK_H
#define KOBUKI_FLEET_MSGS_MESSAGE_GETCURRENTTASK_H

#include <ros/service_traits.h>


#include <kobuki_fleet_msgs/GetCurrentTaskRequest.h>
#include <kobuki_fleet_msgs/GetCurrentTaskResponse.h>


namespace kobuki_fleet_msgs
{

struct GetCurrentTask
{

typedef GetCurrentTaskRequest Request;
typedef GetCurrentTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentTask
} // namespace kobuki_fleet_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kobuki_fleet_msgs::GetCurrentTask > {
  static const char* value()
  {
    return "7566c2d6497dfafdb82ac945e8c8e663";
  }

  static const char* value(const ::kobuki_fleet_msgs::GetCurrentTask&) { return value(); }
};

template<>
struct DataType< ::kobuki_fleet_msgs::GetCurrentTask > {
  static const char* value()
  {
    return "kobuki_fleet_msgs/GetCurrentTask";
  }

  static const char* value(const ::kobuki_fleet_msgs::GetCurrentTask&) { return value(); }
};


// service_traits::MD5Sum< ::kobuki_fleet_msgs::GetCurrentTaskRequest> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::GetCurrentTask > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::GetCurrentTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::GetCurrentTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::GetCurrentTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::GetCurrentTaskRequest> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::GetCurrentTask > 
template<>
struct DataType< ::kobuki_fleet_msgs::GetCurrentTaskRequest>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::GetCurrentTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::GetCurrentTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kobuki_fleet_msgs::GetCurrentTaskResponse> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::GetCurrentTask > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::GetCurrentTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::GetCurrentTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::GetCurrentTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::GetCurrentTaskResponse> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::GetCurrentTask > 
template<>
struct DataType< ::kobuki_fleet_msgs::GetCurrentTaskResponse>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::GetCurrentTask >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::GetCurrentTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_GETCURRENTTASK_H
