// Generated by gencpp from file kobuki_fleet_msgs/getInventoryData.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_GETINVENTORYDATA_H
#define KOBUKI_FLEET_MSGS_MESSAGE_GETINVENTORYDATA_H

#include <ros/service_traits.h>


#include <kobuki_fleet_msgs/getInventoryDataRequest.h>
#include <kobuki_fleet_msgs/getInventoryDataResponse.h>


namespace kobuki_fleet_msgs
{

struct getInventoryData
{

typedef getInventoryDataRequest Request;
typedef getInventoryDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getInventoryData
} // namespace kobuki_fleet_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kobuki_fleet_msgs::getInventoryData > {
  static const char* value()
  {
    return "d0359135eac7dfdadf776963b7cda6a8";
  }

  static const char* value(const ::kobuki_fleet_msgs::getInventoryData&) { return value(); }
};

template<>
struct DataType< ::kobuki_fleet_msgs::getInventoryData > {
  static const char* value()
  {
    return "kobuki_fleet_msgs/getInventoryData";
  }

  static const char* value(const ::kobuki_fleet_msgs::getInventoryData&) { return value(); }
};


// service_traits::MD5Sum< ::kobuki_fleet_msgs::getInventoryDataRequest> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::getInventoryData > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::getInventoryDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::getInventoryData >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::getInventoryDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::getInventoryDataRequest> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::getInventoryData > 
template<>
struct DataType< ::kobuki_fleet_msgs::getInventoryDataRequest>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::getInventoryData >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::getInventoryDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kobuki_fleet_msgs::getInventoryDataResponse> should match 
// service_traits::MD5Sum< ::kobuki_fleet_msgs::getInventoryData > 
template<>
struct MD5Sum< ::kobuki_fleet_msgs::getInventoryDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kobuki_fleet_msgs::getInventoryData >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::getInventoryDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kobuki_fleet_msgs::getInventoryDataResponse> should match 
// service_traits::DataType< ::kobuki_fleet_msgs::getInventoryData > 
template<>
struct DataType< ::kobuki_fleet_msgs::getInventoryDataResponse>
{
  static const char* value()
  {
    return DataType< ::kobuki_fleet_msgs::getInventoryData >::value();
  }
  static const char* value(const ::kobuki_fleet_msgs::getInventoryDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_GETINVENTORYDATA_H
