// Generated by gencpp from file kobuki_fleet_msgs/ManagerTaskGoal.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_MANAGERTASKGOAL_H
#define KOBUKI_FLEET_MSGS_MESSAGE_MANAGERTASKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kobuki_fleet_msgs/NewTask.h>

namespace kobuki_fleet_msgs
{
template <class ContainerAllocator>
struct ManagerTaskGoal_
{
  typedef ManagerTaskGoal_<ContainerAllocator> Type;

  ManagerTaskGoal_()
    : newTask()
    , taskType(0)  {
    }
  ManagerTaskGoal_(const ContainerAllocator& _alloc)
    : newTask(_alloc)
    , taskType(0)  {
    }



   typedef  ::kobuki_fleet_msgs::NewTask_<ContainerAllocator>  _newTask_type;
  _newTask_type newTask;

   typedef uint8_t _taskType_type;
  _taskType_type taskType;




  typedef boost::shared_ptr< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ManagerTaskGoal_

typedef ::kobuki_fleet_msgs::ManagerTaskGoal_<std::allocator<void> > ManagerTaskGoal;

typedef boost::shared_ptr< ::kobuki_fleet_msgs::ManagerTaskGoal > ManagerTaskGoalPtr;
typedef boost::shared_ptr< ::kobuki_fleet_msgs::ManagerTaskGoal const> ManagerTaskGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kobuki_fleet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'kobuki_fleet_msgs': ['/home/odroid/car-whisper/src/kobuki_fleet/kobuki_fleet_msgs/msg', '/home/odroid/car-whisper/devel/share/kobuki_fleet_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5daab4cb647644d1d86f5a4d6619d92a";
  }

  static const char* value(const ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5daab4cb647644d1ULL;
  static const uint64_t static_value2 = 0xd86f5a4d6619d92aULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/ManagerTaskGoal";
  }

  static const char* value(const ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
kobuki_fleet_msgs/NewTask newTask\n\
\n\
#maybe the taskType is not necesary. Determined in the task\n\
uint8 taskType\n\
#uint8 PRIMARY=1\n\
#uint8 SECONDARY=2\n\
\n\
================================================================================\n\
MSG: kobuki_fleet_msgs/NewTask\n\
Header header\n\
string machineName\n\
string robotName\n\
string destinationName\n\
uint16 taskDeadline    \n\
\n\
uint16 REPLENISHMENT=1\n\
uint16 DELIVERY=2\n\
uint16 GOTO=3\n\
uint16 CALL=4\n\
uint16 taskType     \n\
\n\
uint16 taskStatus\n\
uint16 OPEN=0\n\
uint16 WORKING=1\n\
uint16 FINISHED=2\n\
uint16 ERROR=3\n\
uint16 CANCELLED=4\n\
\n\
uint16 taskMaterialType\n\
uint16 typeA=1\n\
uint16 typeB=2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.newTask);
      stream.next(m.taskType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ManagerTaskGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kobuki_fleet_msgs::ManagerTaskGoal_<ContainerAllocator>& v)
  {
    s << indent << "newTask: ";
    s << std::endl;
    Printer< ::kobuki_fleet_msgs::NewTask_<ContainerAllocator> >::stream(s, indent + "  ", v.newTask);
    s << indent << "taskType: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.taskType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_MANAGERTASKGOAL_H
