// Generated by gencpp from file kobuki_fleet_msgs/setInventoryDataResponse.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_SETINVENTORYDATARESPONSE_H
#define KOBUKI_FLEET_MSGS_MESSAGE_SETINVENTORYDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace kobuki_fleet_msgs
{
template <class ContainerAllocator>
struct setInventoryDataResponse_
{
  typedef setInventoryDataResponse_<ContainerAllocator> Type;

  setInventoryDataResponse_()
    : finished()  {
    }
  setInventoryDataResponse_(const ContainerAllocator& _alloc)
    : finished(_alloc)  {
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _finished_type;
  _finished_type finished;




  typedef boost::shared_ptr< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setInventoryDataResponse_

typedef ::kobuki_fleet_msgs::setInventoryDataResponse_<std::allocator<void> > setInventoryDataResponse;

typedef boost::shared_ptr< ::kobuki_fleet_msgs::setInventoryDataResponse > setInventoryDataResponsePtr;
typedef boost::shared_ptr< ::kobuki_fleet_msgs::setInventoryDataResponse const> setInventoryDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kobuki_fleet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'kobuki_fleet_msgs': ['/home/odroid/car-whisper/src/kobuki_fleet/kobuki_fleet_msgs/msg', '/home/odroid/car-whisper/devel/share/kobuki_fleet_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf7ed30376b785bc54463c4d803f6b95";
  }

  static const char* value(const ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf7ed30376b785bcULL;
  static const uint64_t static_value2 = 0x54463c4d803f6b95ULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/setInventoryDataResponse";
  }

  static const char* value(const ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool finished\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct setInventoryDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kobuki_fleet_msgs::setInventoryDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_SETINVENTORYDATARESPONSE_H
