// Generated by gencpp from file kobuki_fleet_msgs/StateMachineStat.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_STATEMACHINESTAT_H
#define KOBUKI_FLEET_MSGS_MESSAGE_STATEMACHINESTAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kobuki_fleet_msgs
{
template <class ContainerAllocator>
struct StateMachineStat_
{
  typedef StateMachineStat_<ContainerAllocator> Type;

  StateMachineStat_()
    : current_state(0)  {
    }
  StateMachineStat_(const ContainerAllocator& _alloc)
    : current_state(0)  {
    }



   typedef uint16_t _current_state_type;
  _current_state_type current_state;


    enum { INIT = 0u };
     enum { IDLE = 1u };
     enum { NEXT = 2u };
     enum { DRIVE = 3u };
     enum { ERROR = 4u };
 

  typedef boost::shared_ptr< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> const> ConstPtr;

}; // struct StateMachineStat_

typedef ::kobuki_fleet_msgs::StateMachineStat_<std::allocator<void> > StateMachineStat;

typedef boost::shared_ptr< ::kobuki_fleet_msgs::StateMachineStat > StateMachineStatPtr;
typedef boost::shared_ptr< ::kobuki_fleet_msgs::StateMachineStat const> StateMachineStatConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kobuki_fleet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'kobuki_fleet_msgs': ['/home/odroid/car-whisper/src/kobuki_fleet/kobuki_fleet_msgs/msg', '/home/odroid/car-whisper/devel/share/kobuki_fleet_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43d9bd846be30acf07699d2030487694";
  }

  static const char* value(const ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43d9bd846be30acfULL;
  static const uint64_t static_value2 = 0x07699d2030487694ULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/StateMachineStat";
  }

  static const char* value(const ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 INIT=0\n\
uint16 IDLE=1\n\
uint16 NEXT=2\n\
uint16 DRIVE=3\n\
uint16 ERROR=4\n\
uint16 current_state\n\
";
  }

  static const char* value(const ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StateMachineStat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kobuki_fleet_msgs::StateMachineStat_<ContainerAllocator>& v)
  {
    s << indent << "current_state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.current_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_STATEMACHINESTAT_H
