// Generated by gencpp from file kobuki_fleet_msgs/SubTask.msg
// DO NOT EDIT!


#ifndef KOBUKI_FLEET_MSGS_MESSAGE_SUBTASK_H
#define KOBUKI_FLEET_MSGS_MESSAGE_SUBTASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Point.h>

namespace kobuki_fleet_msgs
{
template <class ContainerAllocator>
struct SubTask_
{
  typedef SubTask_<ContainerAllocator> Type;

  SubTask_()
    : subTasktType()
    , serviceArea()
    , poseOrientation(0)
    , serviceAreaHigh(0.0)
    , poseNew()
    , pose()
    , waitingTime()
    , objectType()
    , objectId(0)
    , object2(0)
    , object3(0)
    , containerId(0)  {
    }
  SubTask_(const ContainerAllocator& _alloc)
    : subTasktType(_alloc)
    , serviceArea(_alloc)
    , poseOrientation(0)
    , serviceAreaHigh(0.0)
    , poseNew(_alloc)
    , pose(_alloc)
    , waitingTime()
    , objectType(_alloc)
    , objectId(0)
    , object2(0)
    , object3(0)
    , containerId(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _subTasktType_type;
  _subTasktType_type subTasktType;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _serviceArea_type;
  _serviceArea_type serviceArea;

   typedef uint16_t _poseOrientation_type;
  _poseOrientation_type poseOrientation;

   typedef float _serviceAreaHigh_type;
  _serviceAreaHigh_type serviceAreaHigh;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _poseNew_type;
  _poseNew_type poseNew;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef ros::Duration _waitingTime_type;
  _waitingTime_type waitingTime;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _objectType_type;
  _objectType_type objectType;

   typedef uint16_t _objectId_type;
  _objectId_type objectId;

   typedef uint16_t _object2_type;
  _object2_type object2;

   typedef uint16_t _object3_type;
  _object3_type object3;

   typedef uint16_t _containerId_type;
  _containerId_type containerId;




  typedef boost::shared_ptr< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> const> ConstPtr;

}; // struct SubTask_

typedef ::kobuki_fleet_msgs::SubTask_<std::allocator<void> > SubTask;

typedef boost::shared_ptr< ::kobuki_fleet_msgs::SubTask > SubTaskPtr;
typedef boost::shared_ptr< ::kobuki_fleet_msgs::SubTask const> SubTaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kobuki_fleet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'kobuki_fleet_msgs': ['/home/odroid/car-whisper/src/kobuki_fleet/kobuki_fleet_msgs/msg', '/home/odroid/car-whisper/devel/share/kobuki_fleet_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf4ea2cfd8702568f206b18548c2144d";
  }

  static const char* value(const ::kobuki_fleet_msgs::SubTask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf4ea2cfd8702568ULL;
  static const uint64_t static_value2 = 0xf206b18548c2144dULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kobuki_fleet_msgs/SubTask";
  }

  static const char* value(const ::kobuki_fleet_msgs::SubTask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string subTasktType\n\
string serviceArea\n\
uint16 poseOrientation\n\
float32 serviceAreaHigh\n\
geometry_msgs/Pose poseNew\n\
geometry_msgs/Point pose\n\
duration waitingTime\n\
string objectType\n\
uint16 objectId\n\
uint16 object2\n\
uint16 object3\n\
uint16 containerId\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::kobuki_fleet_msgs::SubTask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subTasktType);
      stream.next(m.serviceArea);
      stream.next(m.poseOrientation);
      stream.next(m.serviceAreaHigh);
      stream.next(m.poseNew);
      stream.next(m.pose);
      stream.next(m.waitingTime);
      stream.next(m.objectType);
      stream.next(m.objectId);
      stream.next(m.object2);
      stream.next(m.object3);
      stream.next(m.containerId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SubTask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_fleet_msgs::SubTask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kobuki_fleet_msgs::SubTask_<ContainerAllocator>& v)
  {
    s << indent << "subTasktType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.subTasktType);
    s << indent << "serviceArea: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.serviceArea);
    s << indent << "poseOrientation: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.poseOrientation);
    s << indent << "serviceAreaHigh: ";
    Printer<float>::stream(s, indent + "  ", v.serviceAreaHigh);
    s << indent << "poseNew: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.poseNew);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "waitingTime: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.waitingTime);
    s << indent << "objectType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objectType);
    s << indent << "objectId: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.objectId);
    s << indent << "object2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object2);
    s << indent << "object3: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object3);
    s << indent << "containerId: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.containerId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOBUKI_FLEET_MSGS_MESSAGE_SUBTASK_H
