// Generated by gencpp from file neocortec/neocortecSendData.msg
// DO NOT EDIT!


#ifndef NEOCORTEC_MESSAGE_NEOCORTECSENDDATA_H
#define NEOCORTEC_MESSAGE_NEOCORTECSENDDATA_H

#include <ros/service_traits.h>


#include <neocortec/neocortecSendDataRequest.h>
#include <neocortec/neocortecSendDataResponse.h>


namespace neocortec
{

struct neocortecSendData
{

typedef neocortecSendDataRequest Request;
typedef neocortecSendDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct neocortecSendData
} // namespace neocortec


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neocortec::neocortecSendData > {
  static const char* value()
  {
    return "6c02cb841862df337a17ec959d566f8f";
  }

  static const char* value(const ::neocortec::neocortecSendData&) { return value(); }
};

template<>
struct DataType< ::neocortec::neocortecSendData > {
  static const char* value()
  {
    return "neocortec/neocortecSendData";
  }

  static const char* value(const ::neocortec::neocortecSendData&) { return value(); }
};


// service_traits::MD5Sum< ::neocortec::neocortecSendDataRequest> should match 
// service_traits::MD5Sum< ::neocortec::neocortecSendData > 
template<>
struct MD5Sum< ::neocortec::neocortecSendDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neocortec::neocortecSendData >::value();
  }
  static const char* value(const ::neocortec::neocortecSendDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neocortec::neocortecSendDataRequest> should match 
// service_traits::DataType< ::neocortec::neocortecSendData > 
template<>
struct DataType< ::neocortec::neocortecSendDataRequest>
{
  static const char* value()
  {
    return DataType< ::neocortec::neocortecSendData >::value();
  }
  static const char* value(const ::neocortec::neocortecSendDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neocortec::neocortecSendDataResponse> should match 
// service_traits::MD5Sum< ::neocortec::neocortecSendData > 
template<>
struct MD5Sum< ::neocortec::neocortecSendDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neocortec::neocortecSendData >::value();
  }
  static const char* value(const ::neocortec::neocortecSendDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neocortec::neocortecSendDataResponse> should match 
// service_traits::DataType< ::neocortec::neocortecSendData > 
template<>
struct DataType< ::neocortec::neocortecSendDataResponse>
{
  static const char* value()
  {
    return DataType< ::neocortec::neocortecSendData >::value();
  }
  static const char* value(const ::neocortec::neocortecSendDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEOCORTEC_MESSAGE_NEOCORTECSENDDATA_H
