// Generated by gencpp from file neocortec/neocortecData.msg
// DO NOT EDIT!


#ifndef NEOCORTEC_MESSAGE_NEOCORTECDATA_H
#define NEOCORTEC_MESSAGE_NEOCORTECDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neocortec
{
template <class ContainerAllocator>
struct neocortecData_
{
  typedef neocortecData_<ContainerAllocator> Type;

  neocortecData_()
    : header()
    , nodeId(0)
    , port(0)
    , data()  {
    }
  neocortecData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nodeId(0)
    , port(0)
    , data(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _nodeId_type;
  _nodeId_type nodeId;

   typedef uint8_t _port_type;
  _port_type port;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::neocortec::neocortecData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neocortec::neocortecData_<ContainerAllocator> const> ConstPtr;

}; // struct neocortecData_

typedef ::neocortec::neocortecData_<std::allocator<void> > neocortecData;

typedef boost::shared_ptr< ::neocortec::neocortecData > neocortecDataPtr;
typedef boost::shared_ptr< ::neocortec::neocortecData const> neocortecDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neocortec::neocortecData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neocortec::neocortecData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neocortec

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'neocortec': ['/home/odroid/car-whisper/src/kobuki_fleet/neocortec/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neocortec::neocortecData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neocortec::neocortecData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neocortec::neocortecData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neocortec::neocortecData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neocortec::neocortecData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neocortec::neocortecData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neocortec::neocortecData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1087d485e7bd2ac6b2e70a18ad6fa12";
  }

  static const char* value(const ::neocortec::neocortecData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1087d485e7bd2acULL;
  static const uint64_t static_value2 = 0x6b2e70a18ad6fa12ULL;
};

template<class ContainerAllocator>
struct DataType< ::neocortec::neocortecData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neocortec/neocortecData";
  }

  static const char* value(const ::neocortec::neocortecData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neocortec::neocortecData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 nodeId\n\
uint8 port\n\
uint8[] data\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::neocortec::neocortecData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neocortec::neocortecData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nodeId);
      stream.next(m.port);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct neocortecData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neocortec::neocortecData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neocortec::neocortecData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nodeId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nodeId);
    s << indent << "port: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.port);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEOCORTEC_MESSAGE_NEOCORTECDATA_H
