(cl:defpackage neocortec-srv
  (:use )
  (:export
   "NEOCORTECSENDDATA"
   "<NEOCORTECSENDDATA-REQUEST>"
   "NEOCORTECSENDDATA-REQUEST"
   "<NEOCORTECSENDDATA-RESPONSE>"
   "NEOCORTECSENDDATA-RESPONSE"
  ))

