# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kobuki_fleet_msgs/ManagerTaskGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kobuki_fleet_msgs.msg
import std_msgs.msg

class ManagerTaskGoal(genpy.Message):
  _md5sum = "5daab4cb647644d1d86f5a4d6619d92a"
  _type = "kobuki_fleet_msgs/ManagerTaskGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
kobuki_fleet_msgs/NewTask newTask

#maybe the taskType is not necesary. Determined in the task
uint8 taskType
#uint8 PRIMARY=1
#uint8 SECONDARY=2

================================================================================
MSG: kobuki_fleet_msgs/NewTask
Header header
string machineName
string robotName
string destinationName
uint16 taskDeadline    

uint16 REPLENISHMENT=1
uint16 DELIVERY=2
uint16 GOTO=3
uint16 CALL=4
uint16 taskType     

uint16 taskStatus
uint16 OPEN=0
uint16 WORKING=1
uint16 FINISHED=2
uint16 ERROR=3
uint16 CANCELLED=4

uint16 taskMaterialType
uint16 typeA=1
uint16 typeB=2

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['newTask','taskType']
  _slot_types = ['kobuki_fleet_msgs/NewTask','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       newTask,taskType

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ManagerTaskGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.newTask is None:
        self.newTask = kobuki_fleet_msgs.msg.NewTask()
      if self.taskType is None:
        self.taskType = 0
    else:
      self.newTask = kobuki_fleet_msgs.msg.NewTask()
      self.taskType = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.newTask.header.seq, _x.newTask.header.stamp.secs, _x.newTask.header.stamp.nsecs))
      _x = self.newTask.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.newTask.machineName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.newTask.robotName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.newTask.destinationName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4HB.pack(_x.newTask.taskDeadline, _x.newTask.taskType, _x.newTask.taskStatus, _x.newTask.taskMaterialType, _x.taskType))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.newTask is None:
        self.newTask = kobuki_fleet_msgs.msg.NewTask()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.newTask.header.seq, _x.newTask.header.stamp.secs, _x.newTask.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.newTask.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.machineName = str[start:end].decode('utf-8')
      else:
        self.newTask.machineName = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.robotName = str[start:end].decode('utf-8')
      else:
        self.newTask.robotName = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.destinationName = str[start:end].decode('utf-8')
      else:
        self.newTask.destinationName = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.newTask.taskDeadline, _x.newTask.taskType, _x.newTask.taskStatus, _x.newTask.taskMaterialType, _x.taskType,) = _struct_4HB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.newTask.header.seq, _x.newTask.header.stamp.secs, _x.newTask.header.stamp.nsecs))
      _x = self.newTask.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.newTask.machineName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.newTask.robotName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.newTask.destinationName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4HB.pack(_x.newTask.taskDeadline, _x.newTask.taskType, _x.newTask.taskStatus, _x.newTask.taskMaterialType, _x.taskType))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.newTask is None:
        self.newTask = kobuki_fleet_msgs.msg.NewTask()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.newTask.header.seq, _x.newTask.header.stamp.secs, _x.newTask.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.newTask.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.machineName = str[start:end].decode('utf-8')
      else:
        self.newTask.machineName = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.robotName = str[start:end].decode('utf-8')
      else:
        self.newTask.robotName = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.newTask.destinationName = str[start:end].decode('utf-8')
      else:
        self.newTask.destinationName = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.newTask.taskDeadline, _x.newTask.taskType, _x.newTask.taskStatus, _x.newTask.taskMaterialType, _x.taskType,) = _struct_4HB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_4HB = struct.Struct("<4HB")
