(cl:in-package kobuki_fleet_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MACHINENAME-VAL
          MACHINENAME
          ROBOTNAME-VAL
          ROBOTNAME
          ROBOTPRIMARY-VAL
          ROBOTPRIMARY
          ROBOTSECONDARY-VAL
          ROBOTSECONDARY
          DESTINATIONNAME-VAL
          DESTINATIONNAME
          SRCNAME-VAL
          SRCNAME
          ROBOTPOSE-VAL
          ROBOTPOSE
          MACHINEPOSE-VAL
          MACHINEPOSE
          SRCPOSE-VAL
          SRCPOSE
          DESTINATIONPOSE-VAL
          DESTINATIONPOSE
          TASKSTATUS-VAL
          TASKSTATUS
          TASKTYPE-VAL
          TASKTYPE
          TASKMATERIALTYPE-VAL
          TASKMATERIALTYPE
))