; Auto-generated. Do not edit!


(cl:in-package kobuki_fleet_msgs-msg)


;//! \htmlinclude ManagerTaskGoal.msg.html

(cl:defclass <ManagerTaskGoal> (roslisp-msg-protocol:ros-message)
  ((newTask
    :reader newTask
    :initarg :newTask
    :type kobuki_fleet_msgs-msg:NewTask
    :initform (cl:make-instance 'kobuki_fleet_msgs-msg:NewTask))
   (taskType
    :reader taskType
    :initarg :taskType
    :type cl:fixnum
    :initform 0))
)

(cl:defclass ManagerTaskGoal (<ManagerTaskGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ManagerTaskGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ManagerTaskGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kobuki_fleet_msgs-msg:<ManagerTaskGoal> is deprecated: use kobuki_fleet_msgs-msg:ManagerTaskGoal instead.")))

(cl:ensure-generic-function 'newTask-val :lambda-list '(m))
(cl:defmethod newTask-val ((m <ManagerTaskGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kobuki_fleet_msgs-msg:newTask-val is deprecated.  Use kobuki_fleet_msgs-msg:newTask instead.")
  (newTask m))

(cl:ensure-generic-function 'taskType-val :lambda-list '(m))
(cl:defmethod taskType-val ((m <ManagerTaskGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kobuki_fleet_msgs-msg:taskType-val is deprecated.  Use kobuki_fleet_msgs-msg:taskType instead.")
  (taskType m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ManagerTaskGoal>) ostream)
  "Serializes a message object of type '<ManagerTaskGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'newTask) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'taskType)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ManagerTaskGoal>) istream)
  "Deserializes a message object of type '<ManagerTaskGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'newTask) istream)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'taskType)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ManagerTaskGoal>)))
  "Returns string type for a message object of type '<ManagerTaskGoal>"
  "kobuki_fleet_msgs/ManagerTaskGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ManagerTaskGoal)))
  "Returns string type for a message object of type 'ManagerTaskGoal"
  "kobuki_fleet_msgs/ManagerTaskGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ManagerTaskGoal>)))
  "Returns md5sum for a message object of type '<ManagerTaskGoal>"
  "5daab4cb647644d1d86f5a4d6619d92a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ManagerTaskGoal)))
  "Returns md5sum for a message object of type 'ManagerTaskGoal"
  "5daab4cb647644d1d86f5a4d6619d92a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ManagerTaskGoal>)))
  "Returns full string definition for message of type '<ManagerTaskGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%kobuki_fleet_msgs/NewTask newTask~%~%#maybe the taskType is not necesary. Determined in the task~%uint8 taskType~%#uint8 PRIMARY=1~%#uint8 SECONDARY=2~%~%================================================================================~%MSG: kobuki_fleet_msgs/NewTask~%Header header~%string machineName~%string robotName~%string destinationName~%uint16 taskDeadline    ~%~%uint16 REPLENISHMENT=1~%uint16 DELIVERY=2~%uint16 GOTO=3~%uint16 CALL=4~%uint16 taskType     ~%~%uint16 taskStatus~%uint16 OPEN=0~%uint16 WORKING=1~%uint16 FINISHED=2~%uint16 ERROR=3~%uint16 CANCELLED=4~%~%uint16 taskMaterialType~%uint16 typeA=1~%uint16 typeB=2~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ManagerTaskGoal)))
  "Returns full string definition for message of type 'ManagerTaskGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%kobuki_fleet_msgs/NewTask newTask~%~%#maybe the taskType is not necesary. Determined in the task~%uint8 taskType~%#uint8 PRIMARY=1~%#uint8 SECONDARY=2~%~%================================================================================~%MSG: kobuki_fleet_msgs/NewTask~%Header header~%string machineName~%string robotName~%string destinationName~%uint16 taskDeadline    ~%~%uint16 REPLENISHMENT=1~%uint16 DELIVERY=2~%uint16 GOTO=3~%uint16 CALL=4~%uint16 taskType     ~%~%uint16 taskStatus~%uint16 OPEN=0~%uint16 WORKING=1~%uint16 FINISHED=2~%uint16 ERROR=3~%uint16 CANCELLED=4~%~%uint16 taskMaterialType~%uint16 typeA=1~%uint16 typeB=2~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ManagerTaskGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'newTask))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ManagerTaskGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ManagerTaskGoal
    (cl:cons ':newTask (newTask msg))
    (cl:cons ':taskType (taskType msg))
))
